/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codificador;

/**
 *
 * @author Tarcyo
 */
public class TelaDoCodificador extends javax.swing.JFrame {

    /**
     * Creates new form TelaDoCodificador
     */
    public TelaDoCodificador() {
        initComponents();
        this.setTitle("Codificador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        painel = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Codificar/Decodificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(painel);

        jLabel1.setText("Digite Aqui:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jButton1)
                .addGap(0, 244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String texto=painel.getText();
    String retorno="";
    char texto2[]=texto.toCharArray();
    for(int i=0;i<texto2.length;i++){
        if(texto2[i]=='A'){
            retorno=retorno+'P';
        }
         if(texto2[i]=='B'){
            retorno=retorno+'Q';
        }
          if(texto2[i]=='C'){
            retorno=retorno+'R';
        }
           if(texto2[i]=='D'){
            retorno=retorno+'S';
            
        }
            if(texto2[i]=='E'){
            retorno=retorno+'T';
        }
             if(texto2[i]=='F'){
            retorno=retorno+'U';
        }
            if(texto2[i]=='G'){
            retorno=retorno+'V';
        }
            if(texto2[i]=='H'){
            retorno=retorno+'W';
        }
             if(texto2[i]=='I'){
            retorno=retorno+'X';
        }
              if(texto2[i]=='J'){
            retorno=retorno+'Y';
        }
               if(texto2[i]=='K'){
            retorno=retorno+'Z';
        }
                if(texto2[i]=='L'){
            retorno=retorno+'@';
        }
                 if(texto2[i]=='M'){
            retorno=retorno+' ';
        }
                  if(texto2[i]=='N'){
            retorno=retorno+'>';
        }
                  
                    if(texto2[i]=='O'){
            retorno=retorno+'<';
        }
                     if(texto2[i]=='P'){
            retorno=retorno+'A';
            
        }
                      if(texto2[i]=='Q'){
            retorno=retorno+'B';
        }
                       if(texto2[i]=='R'){
            retorno=retorno+'C';
        }
                        if(texto2[i]=='S'){
            retorno=retorno+'D';
        }
                         if(texto2[i]=='T'){
            retorno=retorno+'E';
        }
                          if(texto2[i]=='U'){
            retorno=retorno+'F';
        }
              if(texto2[i]=='V'){
            retorno=retorno+'G';
        }   
                    if(texto2[i]=='W'){
            retorno=retorno+'H';
        }  
                           if(texto2[i]=='X'){
            retorno=retorno+'I';
        }
                            if(texto2[i]=='Y'){
            retorno=retorno+'J';
        }
                             if(texto2[i]=='Z'){
            retorno=retorno+'K';
        
               
                          
                     
    }
                                   if(texto2[i]==' '){
            retorno=retorno+'M';
        }  
                                         if(texto2[i]=='>'){
            retorno=retorno+'N';
        }  
                                               if(texto2[i]=='<'){
            retorno=retorno+'O';
        }
                                                     if(texto2[i]=='@'){
            retorno=retorno+'L';
        }
           if(texto2[i]=='.'){
            retorno=retorno+'1';
        }                                        
             if(texto2[i]==','){
            retorno=retorno+'2';
        }
                if(texto2[i]==';'){
            retorno=retorno+'3';
        }
                   if(texto2[i]=='!'){
            retorno=retorno+'4';
        }
                      if(texto2[i]=='?'){
            retorno=retorno+'5';
        }
                         if(texto2[i]=='"'){
            retorno=retorno+'6';
        }
                            if(texto2[i]=='-'){
            retorno=retorno+'7';
        }
          if(texto2[i]=='1'){
            retorno=retorno+'.';
        }                                        
             if(texto2[i]=='2'){
            retorno=retorno+',';
        }
                if(texto2[i]=='3'){
            retorno=retorno+';';
        }
                   if(texto2[i]=='4'){
            retorno=retorno+'!';
        }
                      if(texto2[i]=='5'){
            retorno=retorno+'?';
        }
                         if(texto2[i]=='6'){
            retorno=retorno+'"';
        }
                            if(texto2[i]=='7'){
            retorno=retorno+'-';
        }              
    }                        
    if(retorno.length()!=0){
        painel.setText(retorno);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoCodificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoCodificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoCodificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoCodificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoCodificador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane painel;
    // End of variables declaration//GEN-END:variables
}
